os: linux
dist: xenial
language: python
addons:
  chrome: stable
jobs:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.0
    - python: "2.7"
      env: PLONE_VERSION=5.1
    - python: "2.7"
      env: PLONE_VERSION=5.2
    - python: "3.7"
      env: PLONE_VERSION=5.2
    - python: "3.8"
      env: PLONE_VERSION=5.2
  fast_finish: true
  allow_failures:
    - python: "3.8"
      env: PLONE_VERSION=5.2
cache:
  pip: true
  directories:
  - eggs
  - downloads
  - buildout-cache
  - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install zc.buildout
  - cp test-$PLONE_VERSION.x.cfg buildout.cfg
install:
  - buildout -N annotate
  - buildout -N
  - pip install zest.pocompile
  - pocompile src
script:
  - bin/code-analysis
  - bin/test --all $TEST_OPTIONS
#  - bin/createcoverage -t '--all $TEST_OPTIONS'
after_success:
#  - pip install -q coveralls
#  - coveralls
