language: python
sudo: false
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install zc.buildout
  - cp test-$PLONE_VERSION.cfg buildout.cfg
  - pip2.7 install popt || pip2.7 install --user  popt
install:
  - buildout -N annotate
  - buildout -N
  - pip install zest.pocompile
  - pocompile src
script:
  - bin/code-analysis
  - bin/test --all $TEST_OPTIONS
  - grep  --include=output.xml -Rl  FAIL parts/test | xargs --no-run-if-empty -n 1 popt
  - bin/createcoverage -t '--all $TEST_OPTIONS'
  - grep  --include=output.xml -Rl  FAIL parts/test | xargs --no-run-if-empty -n 1 popt
after_success:
  - pip install -q coveralls
  - coveralls
